name: "Check Signed Commits in PR"
description: "Reusable GitHub Action to check that all commits in a PR are signed."
author: "FiligranHQ"
inputs:
  comment:
    description: "Comment to post if unsigned commits are found."
    required: false
    default: |
      Thank you for your contribution. This PR is but one step away from being ready for merging: all commits must be PGP-signed. To get started, please see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
runs:
  using: "composite"
  steps:
    - name: Information about how to sign commits
      shell: bash
      run: |
        echo "If you need to sign commits, Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits"
    - name: Check signed commits in PR
      uses: 1Password/check-signed-commits-action@v1
      with:
        comment: ${{ inputs.comment }}
